let idade= 16
let nome= "Renato"
let altura= 1.78
let cor_pele= "pardo"
let sexo= "homem"
let cabelo_Cor= "preta"
let ca_tamanho= "médio"
let ca_tipo= "ondulada"
let fundo_obj="computadores"
let fundo_pessoas="muitas pessoas"












console.log("Olá me chamo " + nome + " tenho " + idade+ " anos, sou um "+ sexo+ " "+ cor_pele+ ", o tamanho do meu cabelo é "+ ca_tamanho+ ", tem a cor "
+ cabelo_Cor+ " sua curvatura é "  +ca_tipo+ ", atrás de mim tem muitos "+ fundo_obj+" e "+ fundo_pessoas+ ".")